=== nickcore/material4/material4-service/src/main/resources/xsd/guide.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vitsoft.by/guide" xmlns:gd="http://www.vitsoft.by/guide" elementFormDefault="qualified">

    <element name="guide" type="gd:Guide"/>

    <complexType name="Guide">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="guideInfo" type="gd:GuideInfo"/>
            <element name="operationalInfo" type="gd:OperationalInfo"/>
            <element name="lookUpInfo" type="gd:LookUpInfo"/>
        </choice>
    </complexType>

    <complexType name="BaseGuideInfo" abstract="true">
        <sequence>
            <element name="description" type="string"/>
            <element name="propertySet" type="gd:PropertySet"/>
            <element name="visiblePropertyNames" type="string"/>
            <element name="popupPropertyNames" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="orderSet" type="gd:OrderSet"/>
            <!--
            <element name="orderPropertyName" type="string"/>
            <element name="ordering" type="string"/>
            -->
        </sequence>
        <attribute name="class" type="gd:Class"/>
        <attribute name="id" type="ID"/>
    </complexType>

    <complexType name="GuideInfo">
        <complexContent>
            <extension base="gd:BaseGuideInfo">
                <sequence>
                    <element name="findProperty" type="string"/>
                    <element name="genName" type="string" minOccurs="0" maxOccurs="1"/>
                    <element name="defFilt" type="string" minOccurs="0" maxOccurs="1"/>
                    <element name="optionSet" type="gd:GuideOptionSet"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Class">
        <restriction base="string"/>
    </simpleType>

    <complexType name="GuideOptionSet">
        <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="option" type="gd:GuideOption"/>
        </sequence>
    </complexType>

   <simpleType name="GuideOption">
        <restriction base="string">
            <!-- опции обычного спр -->
            <enumeration value="Edit"/>
            <enumeration value="Delete"/>
            <enumeration value="Filt"/>
            <enumeration value="Sort"/>
            <enumeration value="Find"/>
            <enumeration value="FindLocal"/>
            <enumeration value="FiltLocal"/>
            <enumeration value="SortLocal"/>
            <enumeration value="FindStd"/>
            <enumeration value="InFind"/>
            <enumeration value="FindEnter"/>
            <enumeration value="FiltNoCheck"/>
            <enumeration value="SetParam"/>
            <enumeration value="Multi"/>
            <!-- опции древовидного спр -->
            <enumeration value="Tree"/>
            <!-- опции справочника с датой (для реестра платежных поручений, ТТН, ...)-->
            <enumeration value="SprDt"/>
            <enumeration value="SprDtInsert"/>
            <enumeration value="SprDtOnlyDok"/>
            <!-- вспомогательные опции -->
            <enumeration value="FindRes"/>
            <enumeration value="Res"/>
            <enumeration value="AddNewElem"/>
            <enumeration value="FindOnShow"/>
        </restriction>
    </simpleType>

    <complexType name="PropertySet">
        <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="property" type="gd:Property"/>
        </sequence>
    </complexType>

    <complexType name="Property">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <!--
            <element name="lookUp" type="gd:LookUpInfoOrRef"/>
            -->
            <element name="lookUp" type="IDREF"/>
        </sequence>
        <attribute name="name" type="string"/>
        <attribute name="displayName" type="string"/>
        <attribute name="defValue" type="string"/>
        <attribute name="width" type="short"/>
        <attribute name="popupWidth" type="short"/>
        <attribute name="lookUp" type="IDREF"/>
    </complexType>

    <complexType name="OrderSet">
        <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="order" type="gd:Order"/>
        </sequence>
    </complexType>

    <complexType name="Order">
        <attribute name="property" type="string"/>
        <attribute name="direction" type="gd:OrderDirection"/>
    </complexType>

   <simpleType name="OrderDirection">
        <restriction base="string">
            <enumeration value="Asc"/>
            <enumeration value="Desc"/>
        </restriction>
    </simpleType>

    <!--
    <complexType name="LookUpInfoOrRef">
        <choice>
            <element name="guideInfo" type="gd:LookUpInfo" />
            <element name="guideInfoRef" type="IDREF" />
        </choice>
    </complexType>
    -->

    <complexType name="OperationalInfo">
        <complexContent>
            <extension base="gd:BaseGuideInfo"/>
        </complexContent>
    </complexType>

    <complexType name="LookUpInfo">
        <sequence>
            <element name="propertyName" type="string"/>
            <element name="resPropertyNames" type="string"/>
            <element name="lookUpResPropertyNames" type="string"/>
            <element name="resCount" type="short"/>
            <element name="changeQuery" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="defFilt" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="showCheck" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="multiCheck" type="string" minOccurs="0" maxOccurs="1"/>
        </sequence>
        <attribute name="id" type="ID"/>
        <attribute name="guideInfo" type="IDREF" />
        <attribute name="lookUpGuideInfo" type="IDREF" />
    </complexType>
</schema>

=== nickcore/material4/material4-service/src/main/resources/guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<guide xmlns="http://www.vitsoft.by/guide" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.vitsoft.by/guide xsd/guide.xsd ">

    <guideInfo id="unit" class="by.vitsoft.material.dto.Unit">
        <description>Справочник едениц измерения</description>
        <propertySet>
            <property name="id" displayName="ИД" width="55"/>
            <property name="unitId" displayName="Код" width="80" popupWidth="5"/>
            <property name="unitName" displayName="Еденица изм." width="90" popupWidth="20"/>
        </propertySet>
        <visiblePropertyNames>unitId,unitName</visiblePropertyNames>
        <popupPropertyNames>unitId,unitName</popupPropertyNames>
        <orderSet>
            <order property="unitName" direction="Asc" />
        </orderSet>
        <findProperty>unitName</findProperty>
        <optionSet>
            <option>Edit</option>
            <option>Filt</option>
            <option>Find</option>
            <option>Sort</option>
            <option>Delete</option>
        </optionSet>
    </guideInfo>

    <guideInfo id="material" class="by.vitsoft.material.dto.Material">
        <description>Справочник материалов</description>
        <propertySet>
            <property name="id" displayName="ИД"/>
            <property name="materialId" displayName="Код" width="5"/>
            <property name="materialName" displayName="Материал" width="25"/>
            <property name="unit.id" displayName="ИД еи"><lookUp>material-unit</lookUp></property>
            <property name="unit.unitId" displayName="Код еи" width="5"/>
            <property name="unit.unitName" displayName="Еденица изм." width="15"/>
            <property/>
        </propertySet>
        <visiblePropertyNames>materialId,materialName,unit.unitId,unit.unitName</visiblePropertyNames>
        <popupPropertyNames>materialId,materialName,unit.unitName</popupPropertyNames>
        <orderSet>
            <order property="materialName" direction="Asc" />
        </orderSet>
        <findProperty>"materialName"</findProperty>
        <optionSet>
            <option>Edit</option>
            <option>Filt</option>
            <option>Find</option>
            <option>Sort</option>
            <option>Delete</option>
        </optionSet>
    </guideInfo>

    <lookUpInfo id="material-unit" guideInfo="material" lookUpGuideInfo="unit">
        <propertyName>unit.unitName</propertyName>
        <resPropertyNames>unit.unitId,unit.unitName,unit.id</resPropertyNames>
        <lookUpResPropertyNames>unitId,unitName,id </lookUpResPropertyNames>
        <resCount>3</resCount>
    </lookUpInfo>
</guide>
